// GENERATED by scripts/sync-version.mjs — do not hand-edit. Edit version.json instead.
export const APP_NAME = "WayerPC";
export const APP_VERSION = "0.2.0";
export const PROTOCOL_VERSION = 1;
export const APP_DESCRIPTION = "Phone ↔ PC transfer over hotspot";
