// Syncs version.json (single source of truth) into the build consumers:
//   1. frontend/src/version.ts  (generated — do not hand-edit)
//   1b. internal/version/version.json (generated mirror for go:embed)
//   2. wails.json info.productVersion (when --wails or always if file exists)
//
// Usage: node scripts/sync-version.mjs [--wails] [--check]
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));

const ver = JSON.parse(readFileSync(join(root, "version.json"), "utf-8"));
if (!/^\d+\.\d+\.\d+$/.test(ver.version)) {
  console.error(`version.json "version" must be semver, got ${JSON.stringify(ver.version)}`);
  process.exit(1);
}

// 1. frontend/src/version.ts (generated — do not hand-edit)
const tsPath = join(root, "frontend", "src", "version.ts");
const ts = `// GENERATED by scripts/sync-version.mjs — do not hand-edit. Edit version.json instead.
export const APP_NAME = ${JSON.stringify(ver.appName)};
export const APP_VERSION = ${JSON.stringify(ver.version)};
export const PROTOCOL_VERSION = ${JSON.stringify(ver.protocolVersion)};
export const APP_DESCRIPTION = ${JSON.stringify(ver.description ?? "")};
`;

// 1b. internal/version/version.json (generated mirror — go:embed forbids
// ".." patterns, so the root file is mirrored here for embedding).
const goMirror = join(root, "internal", "version", "version.json");
const goSrc = readFileSync(join(root, "version.json"), "utf-8");

function checkOrWrite(path, content, label) {
  if (args.has("--check")) {
    if (!existsSync(path) || readFileSync(path, "utf-8") !== content) {
      console.error(`${label} is out of date. Run: node scripts/sync-version.mjs`);
      process.exit(1);
    }
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${path}`);
}

checkOrWrite(tsPath, ts, "frontend/src/version.ts");
checkOrWrite(goMirror, goSrc, "internal/version/version.json");

// 2. wails.json productVersion
const wailsPath = join(root, "wails.json");
if (existsSync(wailsPath)) {
  const w = JSON.parse(readFileSync(wailsPath, "utf-8"));
  w.info = w.info ?? {};
  if (w.info.productVersion !== ver.version) {
    w.info.productVersion = ver.version;
    if (!args.has("--check")) {
      writeFileSync(wailsPath, JSON.stringify(w, null, 2) + "\n");
      console.log(`updated ${wailsPath} productVersion -> ${ver.version}`);
    } else {
      console.error(`wails.json productVersion ${w.info.productVersion} != ${ver.version}`);
      process.exit(1);
    }
  }
}
console.log(`${ver.appName} v${ver.version} (proto ${ver.protocolVersion}) synced`);
